version: "3.9"

services:

    server:
        build:
            context: .
            dockerfile: docker/Dockerfile-server
        ports:
            - "127.0.0.1:80:80"
        networks:
            - academic-assistant-local
        environment:
            - SERVER_ID=1
        restart: always
        command: ["sh", "-c", "flask run --reload --host=0.0.0.0 --port=80"]

networks:
    academic-assistant-local:
        driver: bridge
        external: true